---
title: "Week 6 exercises"
author: "Wing-Ho Ko"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading library


## Exercise 1: formula interface

1. What terms are included in the following models?

  i. Y ~ X1 + X2 * X3

  ii. Y ~ (X1 + X2) * X3 

2. Suppose you have the response variable Y and 3 explanatory variables X1, X2, X3. Write down the formula that includes all main effects ($X_i$) and second order interactions ($X_i X_j$) but not the third order interaction ($X_i X_j X_k$)


## Exercise 2: multiple linear regression on penguin

Consider the penguin dataset. We'll treat body mass as our response variable, and treat bill length, bill depth, and flipper length as our explanatory variables. As usual, drop any observations for which any of these four variables are NA's

1. Model the dependence of body mass (`body_mass_g`) on bill length (`bill_length_mm`), bill depth (`bill_depth_mm`), and flipper length (`flipper_length`) using an additive multiple linear model. Apply the `summary()` function on the resulting model object. Are the overall result statistically significant? What about the individual parameters?

2. Create a figure for model diagnostics, where the residuals are plotted against fitted values. Do you observe any serious violations in model assumptions?

3. Check the Akaike's information criterion of the model in part (1) against the one where the least significant explanatory variable is dropped. Is it advisable to remove the least significant explanatory variable from the model?

4. Consider the additive linear model with the least significant dependence dropped. Compare it with a linear model for which interactions between those remaining variables are included. Is the interaction significant? Is it sensible to keep the interaction?

5. Fix bill depth at 14 mm, and consider flipper length in the range of 190 to 210 mm. Predict the body mass as a function of flipper length using (a) the additive linear model and (b) the interacting model as described in part (4). Illustrate the results in a plot.

Repeat the exercise with bill depth at 18 mm


## Exercise 3: one-way and two-way ANOVAs

Consider the penguin dataset. Focus on body mass as the response variable and the sex and species of penguins as explanatory variables. As usual, subset your dataset so that any NA entries from these columns are removed.

1. Consider the penguin species as the sole explanatory variable. Determine if one-way ANOVA or Kruskal-Wallis test should be performed.

2. Perform the appropriate one-factor test based on your results from (1). Is the difference between species statistically significant?

3. Perform the post-hoc pairwise test consistent with the test you performed in (2). Which pairwise difference is significant?

4. Now consider BOTH species and sex as explanation variables, with possible interactions. Again determine which test is appropriate.

5. Conduct the appropriate test based on your results from (4). Is the interaction significant?


## Exercise 4: multiple linear regression with categorical variables

Consider the penguins dataset again. Focus on the numerical variables (body mass, bill length, bill depth, and flipper length) as well as species. As before we'll treat body mass as the response variable and the remaining variables as explanatory.

1. Suppose we are interested in the how bill depth and species may predict body mass. Fit an additive linear model, and print the summary (use the default treatment contrast). Interpret the coefficients of the summary

2. Determine if the effect of the species variable is statistically significant or not in the above model.

3. Now add the interaction term. Determine if the interaction term is statistically significant in the new model.


## (Optional) Feedback questions

1. Are there any topic(s) from this week that still confuse you?

2. Which activities work and which doesn't? What do you want to see change and what do you want to keep?
