---
title: "Week 6 exercises"
author: "Wing-Ho Ko"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading library


## Exercise 1: simple linear regression on penguins

Consider the penguins dataset. Treat body mass as the response variable and flipper length as the explanatory variable.

1. Subset the penguins dataset to retain only the body mass and flipper length variables, and drop any observations that contain `NA`'s

2. Make a plot of body mass versus flipper length. Use `geom_smooth()` to also add the linear regression line

3. Perform the linear regression. How much does body mass increases per unit increase in flipper length? Also determine if the dependence of body mass on flipper length is statistically significant (= discernible)

4. What is the 95% confidence interval in the slope you find in the previous part?

5. Suppose the flipper length of a penguin is measured to be 204 mm. What is the expected body mass of the penguin? And what is the range of body mass you'd expect to cover the body mass of the penguin 90% of the times?

6. Plot the residuals against the explanatory variable. Is there an overall trend in the mean? Is there heteroscedasticity? Also check normality.


## Exercise 2: formula interface

1. What terms are included in the following models?

  i. Y ~ X1 + X2 * X3

  ii. Y ~ (X1 + X2) * X3 

2. Suppose you have the response variable Y and 3 explanatory variables X1, X2, X3. Write down the formula that includes all main effects ($X_i$) and second order interactions ($X_i X_j$) but not the third order interaction ($X_i X_j X_k$)


## Exercise 3: multiple linear regression on penguin

Consider the penguin dataset. We'll treat body mass as our response variable, and treat bill length, bill depth, and flipper length as our explanatory variables. As usual, drop any observations for which any of these four variables are NA's

1. Model the dependence of body mass (`body_mass_g`) on bill length (`bill_length_mm`), bill depth (`bill_depth_mm`), and flipper length (`flipper_length`) using an additive multiple linear model. Apply the `summary()` function on the resulting model object. Are the overall result statistically significant? What about the individual parameters?

2. Create a figure for model diagnostics, where the residuals are plotted against fitted values. Do you observe any serious violations in model assumptions?

3. Check the Akaike's information criterion of the model in part (1) against the one where the least significant explanatory variable is dropped. Is it advisable to remove the least significant explanatory variable from the model?

4. Consider the additive linear model with the least significant dependence dropped. Compare it with a linear model for which interactions between those remaining variables are included. Is the interaction significant? Is it sensible to keep the interaction?

5. Fix bill depth at 14 mm, and consider flipper length in the range of 190 to 210 mm. Predict the body mass as a function of flipper length using (a) the additive linear model and (b) the interacting model as described in part (4). Illustrate the results in a plot.

Repeat the exercise with bill depth at 18 mm


## (Optional) Feedback questions

1. Are there any topic(s) from this week that still confuse you?

2. Which activities work and which doesn't? What do you want to see change and what do you want to keep?
